# Base
shell zsh

# Font
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Cursor
cursor              #f3f4f6
shell_integration yes
cursor_shape block
cursor_blinking_interval 0.5
cursor_stop_blinking_after 15.0

# Margin
window_margin_width 4 12 12 12

# Colors
foreground          #f3f4f6
background          #101119
selection_background #353b57
selection_foreground #f3f4f6

# Shell colors

# black
color0   #030712
color8   #6a7282

# red
color1   #fb2c36
color9   #ffa2a2

# green
color2    #00c950
color10   #7bf1a8

# yellow
color3    #fe9a00
color11   #ffdf20

# blue
color4   #2b7fff
color12  #8ec5ff

# magenta
color5   #ad46ff
color13  #dab2ff

# cyan
color6   #00b8db
color14  #53eafd

# white
color7   #f3f4f6
color15  #f9fafb